### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by fmeloSP** [tom-daly/spfx-global-navigation#1]
Hi there, i was looking for installation/compiling instructions for this solutions. Is there anything you can point me to?

nando

**Comment by tom-daly** [comment]
It's somewhat complicated. Depending on the level of experience. I am working on a full write up and also make it a little easier if you just want to use it. 

To fully build it you need a [SPFx development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment).  All the pre-requisites such node.js, gulp, and will also need Powershell PnP. It's just an SPFx application customizer project so you would download the code, run npm install to pull in all the required projects. 

Then you would build it just like any SPFx project to get the sppkg file to add to your app catalog inside SharePoint. After it installed and is deployed go to your site and add the spfx-global-navgation app. 

You also need to provision the list as the source. This requires [PnP Powershell](https://github.com/SharePoint/PnP-PowerShell/releases) to be installed. In the provisioning folder run deploy.ps1, that will ask you for site and popup a login to use your credentials to provisioning the list. The list should be hosted on the "/" site aka https://{your-domain}.sharepoint.com/

**Comment by tom-daly** [comment]
adding installation instructions this week. I'll close the issue for now please let me know if anything else is unclear.

**Comment by bhmoss** [comment]
Does the list gets updated if there is any change in the global navigation ?  or it is manual ?
