### ISSUE TITLE
deploy.ps1 is missing from classic-list folder

### ISSUE THREAD

**Issue by iJKTen** [tom-daly/spfx-global-navigation#10]
It appears a powershell script called deploy.ps1 is missing from the classic-list folder. Please can you add that?

**Comment by tom-daly** [comment]
Please use the provisioning file below. It's the same for on prem / online / classic / modern 

https://github.com/tom-daly/spfx-global-navigation/tree/master/provisioning

**Comment by tom-daly** [comment]
added deploy files for classic mode
