### ISSUE TITLE
Space issues coming on the hub site

### ISSUE THREAD

**Issue by navanu1234** [tom-daly/spfx-global-navigation#11]
Hi,

I have added the left side navigation in one of the site collection. The site collection is connected to a hub site. When I am navigating back to the hub site it will have the white space and not refreshing the page. Could you please help.

Enclosing the hub site screenshot for your reference.
![hubsitespaceissue](https://user-images.githubusercontent.com/71001686/92566855-6e2f1780-f2af-11ea-8d94-0859839f6235.png)

**Comment by tom-daly** [comment]
Thanks for the feedback i will take a look at this and report back

**Comment by tom-daly** [comment]
This is the repo for the top navigation, are you using the side navigation project? or is this happening using this project?

**Comment by tom-daly** [comment]
this is an issue for the side navigation repo. closing this issue to address there.
