### ISSUE TITLE
Enhancement Request : Lock Icon for Secure Sites

### ISSUE THREAD

**Issue by amalwayscharan** [tom-daly/spfx-global-navigation#16]
Since it is primarily used for intranet purposes, would be great to have a new column with checkbox "yes/no" in the Global Nav list - mean private/public, private mean "_you need additional permissions or entering a more secure content_" to click on the link. 

Just like Home Icon, we can place "\E9A2" lock Fabric UI icon for the private/secure links.

**Comment by tom-daly** [comment]
Good suggestion. That's easy enough to implement. I've done this before for other clients.

**Comment by amalwayscharan** [comment]
> Good suggestion. That's easy enough to implement. I've done this before for other clients. 

Great! I look forward to seeing it..!

**Comment by tom-daly** [comment]
added it to the o365 version. the provisioning files where also updated so you can rerun the script to add the new column. it will error on the lookup column b/c it already exists.

![image](https://user-images.githubusercontent.com/9259305/108446059-7ced0380-722b-11eb-8ab7-96550fd04083.png)

**Comment by amalwayscharan** [comment]
That's really great! Could you please try to include it over in 2019 version as well when you get a chance? We have an on-premise '19 environment.

**Comment by tom-daly** [comment]
updated 2019 version - this uses office fabric solidshield / the o365 version is using font awesome shield as pictured above.

**Comment by amalwayscharan** [comment]
Works great, Kudos to Tom for his prompt response on this.
