### ISSUE TITLE
Deployed on SP 2019 Modern Communication Site but not showing up

### ISSUE THREAD

**Issue by becko1001** [tom-daly/spfx-global-navigation#19]
Hey, 
i'm trying to deploy the Global Nav to a SP 2019 modern communication site but it's not showing up.

I build the SPPKG and uploaded it to the App-Store. The deploy.ps1 ist just working for classic sites, right? 

Do i have to build list, content type etc. by myself in modern environment or is it coming with adding the app to a site collection?

No error messages etc.

Does it just work, if the root site is classic? Any suggestions? :-)

**Comment by becko1001** [comment]
Hi Thomas,
thanks for the quick answer! I have done that but get an error everytime i ran the script in line 17 with the  "Apply-PnPProvisioningTemplate ".\GlobalNavList\definition.xml" ". In a classic site it works without any issues but in modern i get this error. 

Maybe its because of the PNP-Version? Or any missing SP Feature? 

Do you have any suggestion? :-)

**Comment by tom-daly** [comment]
Is there any more info on that error? it could be the PnP version. This was written for the previous version of PnP PowerShell, there is now a newer version. I'll check it out on my side.

**Comment by tom-daly** [comment]
I updated the script file so it will check if that command exists, if not try the invoke-pnpsitetemplate. This should now work with either version of pnp powershell you have installed.

**Comment by becko1001** [comment]
Thanks for that! I had already tried the "invoke-pnpsitetemplate" but i'll  try the new script these days and give you a feedback on that!

**Comment by becko1001** [comment]
I am now one step further and the script runs without problems. Solution was updating PNP in combination with your new deploying script. 
The list is now created, but only the column "parent" is included in it. All other columns are missing. Is this possibly because the use of content types is not activated?

**Comment by tom-daly** [comment]
That's strange as well. so it never created any of the fields from the xml file. Which version of pnp are you using? the one with apply or invoke [template]? if you want to just get this working you could create the list manually based on the schema internal names and types

**Comment by becko1001** [comment]
I'm using version with Apply-PnPProvisioning template. 
currently it creates the global navigation list for me, but does not add the individual columns there. When I add the columns manually, only a white area appears at the top.

Does the web part not work in SP2019 on a communication site? I have no other idea how to get the webpart to work.

**Comment by tom-daly** [comment]
This web part does work on on prem 2019, as i have it installed in a few environments. Since you had trouble installing the list and created it manually I am unsure if you created the list columns as defined in the schema. 

The column names need to be exact or it won't work. When you create the columns use the internal name and then renamed them. the internal name does not include spaces and the display name would have spaces. It has to be exact or it will not work. 

open the f12 tool bard while the page loads and it might be giving you the error on the column.

**Comment by becko1001** [comment]
It works now. The DevTools were a good hint, thanks for that!

I created the list again completely according to the given schema and then saw via the F12 console that the name of the list must be "Global Nav List", but I had used "GlobalNavList" by mistake.

Thanks for your support! The web part now works perfect!
