### ISSUE TITLE
update in global navigation, how the list gets updated ?

### ISSUE THREAD

**Issue by bhmoss** [tom-daly/spfx-global-navigation#2]

**Comment by bhmoss** [comment]
![10-19-2019 12-45-32 PM](https://user-images.githubusercontent.com/56683438/67142916-b21bc700-f26e-11e9-81fe-63d9a450772c.png)

Getting this error while running gulp serve

**Comment by tom-daly** [comment]
I am not following what the question is. The list you manually add entries to. I'm not seeing any errors related to the code. There are number of errors that just occur naturally in sharepoint ... seeing those CORS errors across many tenants w/ no customizations

my dev tenant no customizations on there
![image](https://user-images.githubusercontent.com/9259305/67149127-7e906b00-f275-11e9-9fed-b08f4df27552.png)

**Comment by bhmoss** [comment]
Thanks for the reply.  The solution is not giving an error. The output is empty. Even if i add manually the items, top navigation is not showing as per the screenshots from you.

I am using spfx version 1.9.1

**Comment by tom-daly** [comment]
In chrome you should see xhr requests to the list. I am assuming thr you have the app installed in app catalog and added to the site as an app first before debugging.

Please confirm you can see xhr request to global nav list

**Comment by bhmoss** [comment]
The app is installed in the App Catalog and added to the site. xhr request to the list is not there.

**Comment by tom-daly** [comment]
If it's installed correctly you will see this call. If you don't see that, then it's not properly installed. 

![image](https://user-images.githubusercontent.com/9259305/67346078-6df92280-f50b-11e9-94fa-37fc5bae20ff.png)

**Comment by bhmoss** [comment]
Instead of showing the menu from the Custom Global Navigation List of the Root Site Collection, Is it possible to fetch from global navigation of the current site or sub site etc ?

**Comment by tom-daly** [comment]
absolutely.. you can replace the provider with another specific provider. 

If you want to pull in the navigation from the current site you can see an example in jQuery in another repo - https://github.com/tom-daly/sp2013-bootstrap-nav/blob/master/src/Style%20Library/topNavigation.js

line 187.. that is the call to get the navigation items of the current site's navigation provider. It will retrieve the OOTB structure nav or MMD navigation. 

you would use that same endpoint in your new provider, and then parse the results to align with IGlobalNavItem
