### ISSUE TITLE
'root' class is conflicting with SP

### ISSUE THREAD

**Issue by mjonila** [tom-daly/spfx-global-navigation#5]
'root' class is in conflict with some SP built-in class name. Therefore when solution is deployed and user goes to Site Contents, the navigation bar gets width and height fixed values (72px, 52px). Please do not use 'root' class name.

**Comment by JasonMichaelRobertson** [comment]
./provisioning/deploy.ps1 does not seem to exist in the Clone

**Comment by tom-daly** [comment]
> ./provisioning/deploy.ps1 does not seem to exist in the Clone

add provisioning folder to root.

**Comment by tom-daly** [comment]
> 'root' class is in conflict with some SP built-in class name. Therefore when solution is deployed and user goes to Site Contents, the navigation bar gets width and height fixed values (72px, 52px). Please do not use 'root' class name.

thanks for the suggestion. I am going to be changing that in the next day or two.
