### ISSUE TITLE
deploy.ps1 is missing from classic-dist folder also

### ISSUE THREAD

**Issue by JasonMichaelRobertson** [tom-daly/spfx-global-navigation#8]

**Comment by JasonMichaelRobertson** [comment]
Thanks for resolving the other issue

**Comment by tom-daly** [comment]
Please use the provisioning file below. It's the same for on prem / online / classic / modern

https://github.com/tom-daly/spfx-global-navigation/tree/master/provisioning

**Comment by tom-daly** [comment]
added deploy files for classic mode
