### ISSUE TITLE
deploy.ps1 missing closing parenthesis on line 5

### ISSUE THREAD

**Issue by bossonservices** [tom-daly/spfx-global-navigation#9]
Hello,
Thanks for all your work! 

I ran into an issue when executing "deploy.ps1" script. The closing parenthesis of the "IF" statement is missing on line 5.

Current code on line 5
`if($siteUrl -like "*$($adfsSiteUrl)*" {`

Correct code with the closing parenthesis 
`if($siteUrl -like "*$($adfsSiteUrl)*") {`

Cheers

**Comment by tom-daly** [comment]
thank you. I quickly removed my site from there and checked it it. I will make fix and repost.
